services:
  mongodb:
    image: mongodb/mongodb-community-server

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000" 
    depends_on:
      - mongodb
    links:
      - mongodb
    environment:
      - MONGO_URL=mongodb://mongodb:27017/csptplayground_db

  frontend:
    build: 
      context: ./frontend
      args:
        - REACT_APP_BACKEND_HOST=localhost
        - REACT_APP_BACKEND_PORT=8000
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
